### ISSUE TITLE
Do not rely on comparisons (Python3 compatibility)

### ISSUE THREAD

**Issue by videlec** [videlec/sage-flatsurf#9]
In Python3 it is not possible anymore to compare arbitrary types. For example one gets
```
**********************************************************************
File "flatsurf/geometry/similarity_surface.py", line 1728, in flatsurf.geometry.similarity_surface.SimilaritySurface.?
Failed example:
    ss = s.delaunay_decomposition(triangulated=True)
Exception raised:
    Traceback (most recent call last):
      File "/opt/sage/sage-py3-gcc/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 681, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/opt/sage/sage-py3-gcc/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 1105, in compile_and_execute
        exec(compiled, globs)
      File "<doctest flatsurf.geometry.similarity_surface.SimilaritySurface.?[6]>", line 1, in <module>
        ss = s.delaunay_decomposition(triangulated=True)
      File "/home/vincent/programming/sage-flatsurf/flatsurf/geometry/similarity_surface.py", line 1769, in delaunay_decomposition
        if (l1<l2 or (l1==l2 and e1<=e2)) and s._edge_needs_join(l1,e1):
    TypeError: '<' not supported between instances of 'int' and 'ExtraLabel'
**********************************************************************
```

**Comment by videlec** [comment]
duplicate of #22
